### ISSUE TITLE
Reset command does not work.

### ISSUE THREAD

**Issue by usandfriends** [p-e-w/finalterm#402]
Based off of this [StackOverflow question](http://askubuntu.com/questions/25077/how-to-really-clear-the-terminal), I was able to completely clear the Terminal by running `reset`. However, `reset` does nothing in Final Term. How would I completely clear a Final Term window?

**Comment by jackiekaye89** [comment]
to clear the terminal aka to empty it of previous text I just enter "clear" without quotations, of course, though it doesn't clear it per se, it just scrolls the thing down to hide previous entries outside the terminal window.

**Comment by usandfriends** [comment]
I know about `clear`, but I'm not asking about scrolling down to not "see" the text, I'm asking about clearing the terminal buffer. Some commands have a ton of output and slow down the terminal, I would like to clear the buffer to speed up the terminal again...

**Comment by jackiekaye89** [comment]
wait, by buffer do you mean the command history thing? I'm not sure if you are or not, but just in case you are the only way that I know of to clear that is to clear the actual file located at "/home/jackiekaye89/.local/share/finalterm/commands.ftcompletion"

I've also discovered that you can write your own 'history' into that file and it will show up, thought that'd be an interesting thing to add as an actual feature, a custom command completion thing with a priority system or whatever.

**Comment by usandfriends** [comment]
I'm not talking about the command history. I'm talking about the text printed onto the console. Is there a command that completely clears the text printed onto the console (renders console "like new", but with the current state of bash)?
